airports/urls.py
# Load path from django.urls
from django.urls import path
# Load applications views.py file
from . import views

#Define url patterns
urlpatterns = [
    # Get index view
    # Example url: /airports/
    path('/', views.index),
    # Show FLight info
    # Example url /flights/search/MYR/ATL
    # the airport_code parameter in the url section
    #   the parameter in the airport_info function
    path('/<str:airport_code>', views.airport_info),

]

csci409/urls.py
from django.contrib import admin
from django.urls import include, path

import airports.views
import flights.views
import routes.views
import tickets.views

urlpatterns = [
    path('', airports.views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('airports', include('airports.urls')),
    path('flights', include('flights.urls')),
    path('routes', include('routes.urls')),
    path('tickets', include('tickets.urls'))

]

routes/urls.py
# Load path from django.urls
from django.urls import path
# Load applications views.py file
from . import views

#Define url patterns
urlpatterns = [
    # Get index view
    # Example url: /airports/
    path('/', views.index),
    # Show FLight info
    # Example url /flights/search/MYR/ATL
    # the airport_code parameter in the url section
    #   the parameter in the airport_info function
    path('/<str:route_request>/<str:route_origin>/<str:route_destination>', views.route_search),

]

airports/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    name = models.CharField(max_length=255)
    airport_code = models.CharField(max_length=3)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5)
    is_open = models.BooleanField()

class Runway(models.Model):
    # Runway Designation
    LEFT = 'L'
    CENTER = 'C'
    RIGHT = 'R'
    NONE = 'N'
    RUNWAY_DESIGNATION_CHOICES = [
        (LEFT, 'Left'),
        (CENTER, 'Center'),
        (RIGHT, 'Right'),
        (NONE, 'None'),
    ]
    runway_number = models.IntegerField()
    runway_designation = models.CharField(
        max_length = 1,
        choices=RUNWAY_DESIGNATION_CHOICES,
        default=NONE
    )
    length = models.IntegerField()
    width = models.IntegerField()
    airport = models.ForeignKey(Airport, on_delete=models.CASCADE)

airports/views.py
from django.http import HttpResponse
from django.shortcuts import render
from tickets.forms import TicketForm
from tickets.models import Reservation
from .models import Airport
from .models import Runway

def index(request):
    # Fetch all airports from database
    airports = Airport.objects.all()
    # Place all airports into a context variable for retrieval in the view
    context = {'airports': airports}
    return render(request, 'airports/index.html', context)


def airport_info(request, airport_code):
    # Fetch the airport by a certain code
    # We should use get, only expecting one airport per code
    airports = Airport.objects.filter(airport_code=airport_code)
    # Filter for the airport variables
    # Display airport name and code
    context = {'airports': airports}
    # return HttpResponse('Showing info for airport: ' + airport.name + "- " + airport.airport_code)
    return render(request, 'airports/airport.html', context)

def search(request):
    form = TicketForm(request.POST)
    if form.is_valid():
        reservation = Reservation.objects.get(id=form.cleaned_data['confirmation_number'])
        return render(request, 'tickets/ticket_search.html', {'reservation': reservation})

airports/templates/airports/airport.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<!-- Q1. Inside the h1 tag display the airport_code- airport name -->
<h1>
    {% for airport in airports %}
        {{airport.airport_code}} - {{airport.name}}
    {%endfor%}

</h1>
<!-- Display the airport address -->
<h2>Address</h2>
<p>
    {% for airport in airports %}
        {{airport.address}} {{airport.city}}, {{airport.state}} {{airport.zipcode}}
    {% endfor %}
</p>
<h2>Runways</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Runway</th>
            <th scope="col">Length</th>
            <th scope="col">Width</th>
        </tr>
    </thead>
    <tbody>
        <!-- Q3 Display the runway number along with designation L,C,R, etc. -->
        <!-- Runway length and width  in a table row-->
        {% for runway in airports.runway_set.all %} <!-- this is a new type of object it will fetch all of the associated runways -->
        <tr>
            <td>{{runway.runway_number}}{{runway.runway_designation}}</td>
            <td>{{runway.length}}</td>
            <td>{{runway.width}}</td>
        </tr>

        {% endfor %}
    </tbody>
</table>
{% endblock %}

airports/templates/airports/index.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<h1>Airports</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Airport Code</th>
            <th scope="col">Airport Name</th>
            <th scope="col">More Information</th>
        </tr>
    </thead>
    <tbody>
        {% for airport in airports %} <!-- Loop through airports from the context variable specified in views.py -->
            <tr>
                <td>{{ airport.airport_code }}</td>
                <td>{{ airport.name }}</td>
                <td><a href="/airports/{{ airport.airport_code }}">More Information</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}